services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - server-net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '55MB'
  server1: &server
    build:
      context: .
      dockerfile: ./src/server/Dockerfile
    restart: always
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - server-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '110MB'
    depends_on:
      - redis
  server2:
    <<: *server
  worker:
    build:
      context: .
      dockerfile: ./src/worker/Dockerfile
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - server-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '65MB'
    depends_on:
      - redis
      - server1
      - server2
  nginx:
    image: nginx:alpine
    container_name: loadbalancer
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 9999:80
    networks:
      - server-net
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '10MB'
    depends_on:
      - redis
      - server1
      - server2
      - worker
networks:
  server-net:
    driver: bridge
  payment-processor:
    external: true
